create table if not exists members
(
    id                bigint generated by default as identity,
    email             varchar(255) not null,
    display_name      varchar(255) not null,
    profile_image_url varchar(255) not null,
    social_type       varchar(255) not null,
    created_at        timestamp    not null,
    updated_at        timestamp    not null,
    primary key (id)
);

create table if not exists categories
(
    id         bigint generated by default as identity,
    name       varchar(255) not null,
    personal   boolean      not null,
    members_id bigint       not null,
    created_at timestamp    not null,
    updated_at timestamp    not null,
    primary key (id),
    foreign key (members_id) references members (id)
);

create table if not exists subscriptions
(
    id            bigint generated by default as identity,
    color         varchar(255) not null,
    checked       boolean      not null,
    members_id    bigint       not null,
    categories_id bigint       not null,
    created_at    timestamp    not null,
    updated_at    timestamp    not null,
    primary key (id),
    foreign key (members_id) references members (id),
    foreign key (categories_id) references categories (id)
);

create table if not exists schedules
(
    id              bigint generated by default as identity,
    title           varchar(255) not null,
    start_date_time timestamp    not null,
    end_date_time   timestamp    not null,
    memo            varchar(255) not null,
    categories_id   bigint       not null,
    created_at      timestamp    not null,
    updated_at      timestamp    not null,
    primary key (id),
    foreign key (categories_id) references categories (id)
);

create table if not exists oauth_tokens
(
    id            bigint generated by default as identity,
    refresh_token varchar(255) not null,
    members_id    bigint       not null,
    created_at    timestamp    not null,
    updated_at    timestamp    not null,
    primary key (id),
    foreign key (members_id) references members (id)
);
