CREATE TABLE IF NOT EXISTS members (
  id BIGINT generated BY DEFAULT AS identity,
  email VARCHAR(255) NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  profile_image_url VARCHAR(255) NOT NULL,
  social_type VARCHAR(255) NOT NULL,
  created_at timestamp NOT NULL,
  updated_at timestamp NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT generated BY DEFAULT AS identity,
  name VARCHAR(255) NOT NULL,
  members_id BIGINT NOT NULL,
  category_type VARCHAR(255) NOT NULL,
  created_at timestamp NOT NULL,
  updated_at timestamp NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (members_id) REFERENCES members (id)
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id BIGINT generated BY DEFAULT AS identity,
  color VARCHAR(255) NOT NULL,
  checked boolean NOT NULL,
  members_id BIGINT NOT NULL,
  categories_id BIGINT NOT NULL,
  created_at timestamp NOT NULL,
  updated_at timestamp NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (members_id) REFERENCES members (id),
  FOREIGN KEY (categories_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS schedules (
  id BIGINT generated BY DEFAULT AS identity,
  title VARCHAR(255) NOT NULL,
  start_date_time timestamp NOT NULL,
  end_date_time timestamp NOT NULL,
  memo VARCHAR(255) NOT NULL,
  categories_id BIGINT NOT NULL,
  created_at timestamp NOT NULL,
  updated_at timestamp NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (categories_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS oauth_tokens (
  id BIGINT generated BY DEFAULT AS identity,
  refresh_token VARCHAR(255) NOT NULL,
  members_id BIGINT NOT NULL,
  created_at timestamp NOT NULL,
  updated_at timestamp NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (members_id) REFERENCES members (id)
);
